#!/usr/bin/env bash

undodir="$HOME/.local/share/nvim/undodir"

function check()
{
	filename="$(echo "$1" | sed 's/%/\//g')"
	[[ ! -f "$filename" ]] && rm "$undodir/$1"
}

find "$undodir" -type f -ctime +30 -delete

readarray -t files < <(ls "$undodir")
for f in "${files[@]}"; do
	check "$f"
done
