#!/usr/bin/env bash

aur_list="/tmp/packages.gz"

if [[ ! -f "$aur_list" ]]; then
	curl -s "https://aur.archlinux.org/packages.gz" > "$aur_list"
else
	now=$(date +"%s")
	pkg_time=$(stat -c "%Y" packages.gz)
	diff=$(( now - pkg_time ))
	[[ $diff -gt 86400 ]] &&
		curl -s "https://aur.archlinux.org/packages.gz" > "$aur_list"
fi

[[ -f "$aur_list" ]] &&
	zcat "$aur_list" | fzf -m --preview="auracle info {}" | tr '\n' ' '
