#!/usr/bin/env bash

core_temp_path=$(find /sys/devices -type f -name "temp*_input" \
	| grep virtual | head -n1)
[[ -n "$core_temp_path" ]] && cores_temp=$(cat "$core_temp_path" | cut -c1,2)

printf "$cores_temp°\n"
