#!/usr/bin/env bash

interface=$(ip route | awk '/^default/ { print $5 ; exit }')
[[ -z "$interface" ]] && exit 1

if ! [[ -e "/sys/class/net/${interface}/operstate" ]] ||
    (! [[ "$TREAT_UNKNOWN_AS_UP" = "1" ]] &&
    ! [[ "$(cat /sys/class/net/${interface}/operstate)" = "up" ]])
then
    exit 1
fi

data="$(sudo pacman -Syup | grep '^https')"
count="$(echo "$data" | wc -l)"

if echo "$data" | grep -q "linux-.*arch" ; then
	echo " $count"
elif [[ "$count" -gt 9 ]]; then
	echo "$count"
fi
