#!/usr/bin/env bash

interface=$(ip route | awk '/^default/ { print $5 ; exit }')
[[ -z "$interface" ]] && exit 1

if ! [[ -e "/sys/class/net/${interface}/operstate" ]] ||
    (! [[ "$TREAT_UNKNOWN_AS_UP" = "1" ]] &&
    ! [[ "$(cat /sys/class/net/${interface}/operstate)" = "up" ]])
then
    exit 1
fi

pacman_upd="$(checkupdates)"
count="$(echo $pacman_upd | wc -l)"
if echo "$pacman_upd" | grep -q "linux-.*arch" ; then
	echo -n " $count"
elif [[ "$count" -gt 9 ]]; then
	echo -n "$count"
fi

aur_upd="$(auracle outdated | wc -l)"
if [[ -n "$aur_upd" ]]; then
	[[ "$count" -gt 9 ]] && echo -n " "
	echo " $aur_upd"
fi
