#!/bin/sh

source $XDG_CONFIG_HOME/X11/xprofile

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

dunst &
unclutter &
sxhkd &
redshift &
clipcatd &
xrandr-setup && fehbg

exec bspwm
