#!/bin/sh

source ${XDG_CONFIG_HOME:-$HOME/.config}/X11/xprofile

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

fcitx &
dunst &
unclutter &
redshift &
sxhkd &
pgrep -x dockd > /dev/null || dockd --daemon &
xrandr-setup && fehbg

exec bspwm
