#!/usr/bin/env bash

server="$(curl --silent "https://api.nordvpn.com/v1/servers/recommendations?filters\[country_id\]=74&limit=1" | jq --raw-output '.[].hostname' | cut -d'.' -f1)"

if pgrep -x nordvpnd; then
	notify-send -u low "nordvpnd already exists, proceeding to connect to ${1:-$server}"
else
	expect <<- DONE
		set timeout -1
		spawn systemctl start nordvpnd
		expect "*?assword:*"
		send -- "$(pass user-zijian)"
		send -- "\r"
		expect eof
	DONE
	if systemctl status nordvpnd | grep -q '\bactive'; then
		notify-send -u low "nordvpnd started successfully"
	else
		notify-send -u low "starting nordvpnd failed" && exit 1
	fi
fi

nordvpn connect "${1:-$server}" || notify-send -u low "connection failed"
