#!/usr/bin/env bash

pgrep -x nordvpnd && notify-send -u low "nordvpnd already exists" && exit 1

expect <<- DONE
	set timeout -1
	spawn systemctl start nordvpnd
	expect "*?assword:*"
	send -- "$(pass user-zijian)"
	send -- "\r"
	expect eof
DONE

(systemctl status nordvpnd | grep -q '\bactive' \
	&& notify-send -u low "nordvpnd started successfully") \
	|| (notify-send -u low "starting nordvpnd failed" && exit 1)

(nordvpn connect France && exit 0) \
	|| (notify-send -u low "connection failed" && exit 1)
