#!/bin/sh

get_scale()
{
	resolution="$1"
	if [ "$resolution" = '1920x1080' ]; then
		echo 1.25
	else
		echo 1
	fi
}

displ_status=$(xrandr | grep -o '\bconnected\b' | wc -l)
if [ $displ_status -gt 1 ]
then
	# 4k single external monitor
	xrandr_output="$(xrandr | grep -v 'eDP1')"
	display=$(echo "$xrandr_output" | grep '\bconnected\b' | cut -d' ' -f1)
	mode=$(echo "$xrandr_output" | grep '\bconnected\b' -A1 | tail -n1 \
		| grep -Eo '[[:digit:]]{4}x[[:digit:]]{4}')

	xrandr --output "$display" --primary --mode "$mode" --scale 1 \
		--output eDP1 --off
else
	# integrated display
	display=$(xrandr | grep 'primary' | cut -d' ' -f1)
	mode=$(xrandr | grep -A1 '\bconnected\b' | tail -n1 \
		| grep -Eo '[[:digit:]]{4}x[[:digit:]]{4}')

	xrandr --output "$display" --primary --mode "$mode" \
		--scale "$(get_scale $mode)"
fi
