#!/usr/bin/env bash

shopt -s expand_aliases && source $XDG_CONFIG_HOME/shell/aliasrc || exit 1

all_entries=$(ls | sort)
cached=$(dfs ls-files -c | cut -d'/' -f1 | sort | uniq)
new_entries=$(comm -23 <(echo "$all_entries") <(echo "$cached"))

[[ ! -z new_entries ]] && printf "new entries:\n\n$new_entries\n"
