#! /bin/sh

xsetroot -cursor_name left_ptr
$HOME/.config/polybar/launch.sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor $(xrandr | grep primary | cut -d' ' -f1) -d I II III IV V

bspc config split_ratio			0.50
bspc config border_width		1
bspc config window_gap			40
bspc config normal_border_color		\#1d2021
bspc config focused_border_color	\#d79921

bspc config top_padding			0
bspc config right_padding		0
bspc config bottom_padding		0
bspc config left_padding		0

bspc config single_monocle		true
bspc config borderless_monocle		true
bspc config gapless_monocle		false

bspc rule -a Zathura state=tiled
