#! /bin/sh

xsetroot -cursor_name left_ptr
$XDG_CONFIG_HOME/polybar/launch.sh

primary_mon=$(xrandr | grep '\bconnected primary\b' | head -n1 | cut -d' ' -f1)
bspc monitor "$primary_mon" -d I II III IV V
bspc monitor "$primary_mon" -f
bspc monitor last -r

bspc config single_monocle			true
bspc config borderless_monocle		true

bspc config border_width			2
bspc config window_gap				20
bspc config top_padding				0
bspc config right_padding			0
bspc config bottom_padding			0
bspc config left_padding			0

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

bspc config initial_polarity first_child

bspc config normal_border_color		"$(xrdb -query | grep background | cut -f2)"
bspc config focused_border_color	"$(xrdb -query | grep 'color3\b' | cut -f2)"

command -v altty-auto-pad > /dev/null 2>&1 && altty-auto-pad
