#! /bin/sh

xsetroot -cursor_name left_ptr
$HOME/.config/polybar/launch.sh

bspc monitor \
    $(xrandr | grep '\bconnected\b' | grep -v 'primary' | cut -d' ' -f1) \
    -r
bspc monitor \
    $(xrandr | grep '\bconnected primary\b' \
    | head -n1 | cut -d' ' -f1 | tr -d '\n') \
    -d I II III IV V

bspc query -D | xargs -I{} bspc desktop {} -l monocle

bspc config split_ratio             0.5
bspc config border_width            3
bspc config window_gap              30
bspc config normal_border_color     \#1d2021
bspc config focused_border_color    \#458588
bspc config top_padding             0
bspc config right_padding           0
bspc config bottom_padding          0
bspc config left_padding            0

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

bspc config single_monocle          true
bspc config borderless_monocle      true

bspc rule -a Zathura state=tiled

screenwidth=$(xdpyinfo | awk -F'[ x]+' '/dimensions:/{print $3}')
screenheight=$(xdpyinfo | awk -F'[ x]+' '/dimensions:/{print $4}')
windowwidth=$(("$screenwidth" / 4 * 3))
windowheight=$(("$screenheight" / 9 * 8))
windowx=$(("$screenwidth" / 2 -"$windowwidth" / 2))
windowy=$(("$screenheight" / 2 -"$windowheight" / 2))
bspc rule -a Alacritty rectangle="$windowwidth"x"$windowheight"+"$windowx"+"$windowy"
