#!/usr/bin/env bash

[[ -z "$*" ]] && printf "no arguments given\n" && exit 1

for pkg in "$@"
do
	git -C "$pkg" pull && \
	sh -c "cd $pkg && makepkg -sirc --noconfirm -- && git clean -xfd && git reset --hard HEAD"
done
