#!/usr/bin/env bash

cd ${XDG_CONFIG_HOME-:$HOME/.config}
shopt -s expand_aliases && source $XDG_CONFIG_HOME/shell/aliasrc || exit 1

all_entries=$(ls | sort)
cached=$(dfs ls-files -c | cut -d'/' -f1 | sort | uniq)
new_entries=$(comm -23 <(comm -23 <(echo "$all_entries") <(echo "$cached")) <(cat .gitignore | sort))

if [[ ! -z "$new_entries" ]]; then 
	for entry in $new_entries
	do
		printf "cache this directory [$entry] (y|n)?\n"
		read ret && [[ "$ret" =~ [N|n] ]] \
			&& echo "add $entry to .gitignore" \
			&& echo "$entry" >> .gitignore
	done
	exit 0
else
	exit 1
fi
