#!/usr/bin/env bash

cd ${XDG_CONFIG_HOME-:$HOME/.config} && shopt -s expand_aliases \
	&& source ${XDG_CONFIG_HOME-:$HOME/.config}/shell/aliasrc || exit 1

all_entries=$(ls | sort)
cached=$(dfs ls-files -c | cut -d'/' -f1 | sort | uniq)
new_entries=$(comm -23 <(comm -23 <(echo "$all_entries") <(echo "$cached")) <(sort .gitignore))

if [[ -n "$new_entries" ]]; then 
	for entry in $new_entries
	do
		printf "cache this directory [%s] (y|n)?: " "$entry"
		read ret && if [[ "$ret" =~ [N|n] ]]; then
			printf "remove [%s] (y|n)?: " "$entry"
			read ret && if [[ "$ret" =~ [Y|y] ]]; then
				rm -rf "$entry" && printf -- "-> %s removed\n\n" "$entry"
			else
				printf -- "-> added %s to .gitignore\n\n" "$entry" &&
					echo "$entry" >> .gitignore
			fi
		fi
	done
	exit 0
else
	exit 1
fi
