#!/usr/bin/env bash

toggle()
{
	[[ -z "$1" ]] && exit 1
	path="$1"

	if grep -o "dark" "$path";
	then
		sed -i 's/dark/light/' "$path"
	else
		sed -i 's/light/dark/' "$path"
	fi
}

switch_wp()
{
	if grep -o "dark" "${XDG_CONFIG_HOME:-$HOME/.config}/feh/mode" > /dev/null;
	then
		fehbg -l
	else
		fehbg -d
	fi
}

switch_dunst()
{
	path="${XDG_CONFIG_HOME:-$HOME/.config}/dunst/dunstrc.d"
	mv "$path/00.conf" "$path/02.conf" &&
		mv "$path/01.conf" "$path/00.conf" &&
		mv "$path/02.conf" "$path/01.conf" &&
		killall dunst && dunst &!
}

acty="${XDG_CONFIG_HOME:-$HOME/.config}/alacritty/colors.yml"
nvm="${XDG_CONFIG_HOME:-$HOME/.config}/nvim/lua/config/bg.lua"
tmx="${XDG_CONFIG_HOME:-$HOME/.config}/tmux/colors.conf"
plb="${XDG_CONFIG_HOME:-$HOME/.config}/polybar/colors.ini"
rf="${XDG_CONFIG_HOME:-$HOME/.config}/rofi/colors.rasi"

switch_wp &&
	toggle "$plb" && "${XDG_CONFIG_HOME:-$HOME/.config}/polybar/launch.sh" > /dev/null 2>&1 &&
	toggle "$acty" &&
	toggle "$nvm" &&
	toggle "$tmx" &&
	toggle "$rf" &&
	switch_dunst
