#!/bin/sh

wp_path="$HOME/Dropbox/Pictures/wallpapers"
config_path="${XDG_CONFIG_HOME:-$HOME/.config}/feh"

set_wp()
{
	mode="$config_path/mode"
	[ "$1" = "-d" ] && echo dark > "$mode" && shift
	[ "$1" = "-l" ] && echo light > "$mode" && shift

	cached="$config_path/$(< "$mode")"

	wp_file="$1"
	if [ -n "$wp_file" ];
	then
		[ -f "$wp_path/$wp_file" ] || mv "$wp_file" "$wp_path"
		echo "$wp_path/$wp_file" > "$cached"
	fi

	feh --no-fehbg --bg-scale "$(< "$cached")"
}

[ "$1" = "-n" ] && feh --no-fehbg --bg-scale "$2" && exit
set_wp "$@"
