#!/usr/bin/env bash

dest=${1:-"/mnt/main/.home_backup"}

log=$HOME/homesync.log
rsync -azvhP --delete-excluded --exclude-from "$HOME/.scripts/.rsyncexclude" $HOME $dest >> $log 2>&1

pacman -Qqen > $HOME/.config/Qqen && cp -f $HOME/.config/Qqen $dest
pacman -Qqem > $HOME/.config/Qqem && cp -f $HOME/.config/Qqem $dest
systemctl list-unit-files --state=enabled --user > $HOME/.config/systemd-unit-files-user \
	&& cp -f $HOME/.config/systemd-unit-files-user $dest
systemctl list-unit-files --state=enabled > $HOME/.config/systemd-unit-files \
	&& cp -f $HOME/.config/systemd-unit-files $dest
