#!/usr/bin/env bash

JDTLS_DIR="$XDG_DATA_HOME/jdtls"

JAR="$JDTLS_DIR/plugins/org.eclipse.equinox.launcher_1.6.300.v20210813-1054.jar"
GRADLE_HOME=/usr/share/java/gradle /usr/lib/jvm/default-runtime/bin/java \
  -Declipse.application=org.eclipse.jdt.ls.core.id1 \
  -Dosgi.bundles.defaultStartLevel=4 \
  -Declipse.product=org.eclipse.jdt.ls.core.product \
  -Dlog.protocol=true \
  -Dlog.level=ALL \
  -Xms1g \
  -Xmx2G \
  -jar $(echo "$JAR") \
  -configuration "$JDTLS_DIR/config_linux" \
  -data "${1:-${XDG_DATA_HOME:-$HOME/.local/share}/workspace}" \
  --add-modules=ALL-SYSTEM \
  --add-opens java.base/java.util=ALL-UNNAMED \
  --add-opens java.base/java.lang=ALL-UNNAMED
