#!/usr/bin/env bash

JAR="/usr/share/java/jdtls/plugins/org.eclipse.equinox.launcher_1.6.200.v20210416-2027.jar"
GRADLE_HOME=/usr/share/java/gradle sudo /usr/lib/jvm/default-runtime/bin/java \
  -Declipse.application=org.eclipse.jdt.ls.core.id1 \
  -Dosgi.bundles.defaultStartLevel=4 \
  -Declipse.product=org.eclipse.jdt.ls.core.product \
  -Dlog.protocol=true \
  -Dlog.level=ALL \
  -Xms1g \
  -Xmx2G \
  -jar $(echo "$JAR") \
  -configuration "/usr/share/java/jdtls/config_linux" \
  -data "${1:-$HOME/workspace}" \
  --add-modules=ALL-SYSTEM \
  --add-opens java.base/java.util=ALL-UNNAMED \
  --add-opens java.base/java.lang=ALL-UNNAMED
