#!/usr/bin/env bash

[[ -z "$*" || $# -lt 2 ]] && exit 1

case "$1" in
	"-j"|"--java")
		sed -E -i "0,/SRC_DIR/{s/(SRC_DIR := ).*/\1$2/}" Makefile &&
			mkdir "$2" &&
			printf "%s\n\n%s\n\n\t%s\n\n\t%s\n\t%s\n%s\n" \
			"package $2;" \
			"class Main {" \
			"private static final Solution sol = new Solution();" \
			"public static void main(String[] args) {" "}" "}" > "$2/Main.java" &&
			nvim "$2/Solution.java"
		;;
	"-c")
		echo "waiting for implementation"
		exit 1
		;;
esac
