#!/usr/bin/env bash

[[ -z "$*" || $# -lt 2 ]] && exit 1

case "$1" in
	"-j"|"--java")
		sed -E -i "0,/SRC_DIR/{s/(SRC_DIR := ).*/\1$2/}" makefile &&
			mkdir "$2" &&
			printf "%s\n\n%s\n\n\t%s\n\n\t%s\n\t%s\n%s\n" \
			"package $2;" \
			"class Main {" \
			"private static final Solution sol = new Solution();" \
			"public static void main(String[] args) {" "}" "}" > "$2/Main.java" &&
			printf "%s\n\n" "package $2;" > "$2/Solution.java" &&
			nvim "$2/Solution.java"
		;;
	"-C")
		sed -E -i "0,/SRC_DIR/{s/(SRC_DIR := ).*/\1$2/}" makefile &&
			mkdir "$2" &&
			printf "%s\n\n%s\n{\n}" \
			"#include \"solution.h\"" \
			"int main(int argc, char** argv)" > "$2/main.cpp" &&
			printf "%s\n\n%s\n" \
			"#pragma once" \
			"#include <iostream>" >> "$2/solution.h" &&
			nvim "$2/solution.cpp"
		;;
	*)
		echo "not available"
		exit 1
		;;
esac
