#!/usr/bin/env bash

function print_count() {
	[[ $1 -lt 2 ]] && echo '' && return 1
	bar=""
	for count in $(seq 1 $1); do
		bar="$bar/"
	done
	echo $bar
}

bspc subscribe node_add node_remove node_transfer desktop_focus |
	while read event; do
		node_count=$(bspc query -N -d focused -n .!hidden.window | wc -l)
		print_count $node_count
done
