#!/usr/bin/env bash

pgrep -x nordvpnd > /dev/null 2>&1
[[ "$?" -eq 1 ]] && notify-send -u low "no nordvpnd instance running" && exit 1

notify-send -u low "disconnecting..."
nordvpn disconnect

expect <<- DONE
	set timeout -1
	spawn systemctl stop nordvpnd
	expect "*?assword:*"
	send -- "$(pass user-zijian)"
	send -- "\r"
	expect eof
DONE

systemctl status nordvpnd | grep -E "(inactive|dead)"
status=$?
[ $status -eq 0 ] && notify-send -u low "daemon killed" || \
	(notify-send -u low "failed killing daemon" && exit 1)
exit 0
