#!/usr/bin/env bash

repo_install()
{
	sudo pacman -Syyy archlinux-keyring &&
		sudo pacman -Syu --needed - < $HOME/.config/misc/Qqen
}

aur_install()
{
	aur="$HOME/aur"
	[[ ! -d "$aur" ]] &&
		git clone git@github.com:zijian-x/aur.git "$aur" &&
		git -C "$aur" submodule update --init
	cd "$aur" || exit 1

	read -rp "==> install all aur packages? [y|n] " no_prompt
	pkgs=($(< $HOME/.config/misc/Qqem))
	for pkg in "${pkgs[@]}"; do
		[[ "$no_prompt" =~ n ]] && read -rp "==> build $pkg? [y/n] " ans
		if [[ -z "$ans" ]] || [[ "$ans" =~ [y/Y] ]]; then
			"$HOME/.scripts/aur/aur-build" --noconfirm "$pkg"
		fi
		echo
	done
}

repo_install
aur_install
