#!/usr/bin/env bash

function get_indicator() {
	[[ -z "$1" ]] && return 1
	if [[ "$1" -gt 90 ]]; then
		echo ""
	elif [[ "$1" -gt 55 ]]; then
		echo ""
	elif [[ "$1" -gt 45 ]]; then
		echo ""
	elif [[ "$1" -gt 15 ]]; then
		echo ""
	else
		echo ""
	fi
}

# get data
data="$(sudo tlp-stat -s -b)"
[[ -z "$data" ]] && exit 1

bats=$(echo "$data" | grep '^Charge\b.*%')

# get percents
bat_0="$(echo "$bats" | head -n1 | grep -Eo '[[:digit:]]+\.' | tr -d '.')"
bat_1="$(echo "$bats" | tail -n1 | grep -Eo '[[:digit:]]+\.' | tr -d '.')"

# get icons
bat_0_icon="$(get_indicator $bat_0)"
bat_1_icon="$(get_indicator $bat_1)"

echo -n "$bat_0_icon $bat_0%"
[[ ! -z "$bat_1" ]] && echo -n "  $bat_1_icon $bat_1%"

[[ "$(echo "$data" | grep "^Power source" | sed 's/.* //g')" == "AC" ]] \
	&& echo "  "
exit 0
