#!/usr/bin/env bash

process="$(ps -U $(whoami) | awk '{print $NF}' | sort | uniq | rofi -dmenu -i -sep'\n' -p 'kill')"
[[ -n "$process" ]] && killall "$process" > /dev/null 2>&1 &&
	notify-send -u low " $process"
