#!/usr/bin/env bash

get_cur_desktop_id() {
	cur="$(bspc query -D -d focused --names)"
	case "$cur" in
		"I")
			echo 0
			;;
		"II")
			echo 1
			;;
		"III")
			echo 2
			;;
		"IV")
			echo 3
			;;
		"V")
			echo 4
			;;
	esac
}
# desktop_id=$(get_cur_desktop_id $(bspc query -D -d focused))

global_winlist=$(wmctrl -l)
# local_winlist=$(echo "$global_winlist" | awk -v id=$desktop_id '{ if ($2 == id) print }')

nodes=( $(echo "$global_winlist" | awk '{ print $1 }' | tr '\n' ' ') )
selected=$(echo "$global_winlist"  |
	awk '{ for (i = 1; i <= NF; ++i) { if (i != 1 && i != 3) printf("%s%s", (i == 2) ? $i" |" : $i, (i != NF) ? OFS : ORS) } }' |
	sed -E 's/([0-9]+ \| )(.+) - (.+)/\1\3 - \2/' |
	rofi -dmenu -i -sep'\n' -p jump -format i)

[[ -z $selected ]] && exit 1
bspc node --focus "${nodes[$selected]}"
