#!/usr/bin/env bash

lsusb | grep -i "HHKB" > /dev/null && exit 0

kb_status="$(bluetoothctl info E4:82:08:83:14:68 | grep "Connected" | sed 's/.* //g')"
[[ -z $kb_status || $kb_status = "no" ]] && xmodmap ${XDG_CONFIG_HOME:-$HOME/.config}/X11/Xmodmap
