#!/bin/sh

function get_scale()
{
	resolution="$1"
	if [[ "$resolution" = '1920x1080' ]]; then
		echo 1.25
	else
		echo 1
	fi
}

DP_STATUS=$(xrandr | grep -o '\bconnected\b' | wc -l)
if [[ $DP_STATUS -gt 1 ]]
then
	# tp single monitor
	xrandr --output DP1 --primary --mode 3840x2160 --scale 1 \
		--output eDP1 --off
		# --output eDP1 --mode 1920x1080 --scale 2 --same-as DP1 # duplicate
	# tp duo monitor extend TODO
else
	DISPL=$(xrandr | grep primary | cut -d' ' -f1 | tr -d '\n')
	MODE=$(xrandr | grep -A1 '\bconnected\b' | tail -n1 \
		| grep -Eo '[[:digit:]]{4}x[[:digit:]]{4}')
	SCALE="$(get_scale $MODE)"
	xrandr --output "$DISPL" --primary --mode "$MODE" --scale "$SCALE"
	echo "$DISPL $MODE $SCALE"
fi
