server_endpoint = "/run/user/1000/clipcat/grpc.sock"
finder = "rofi"
preview_length = 80

[rofi]
line_length = 100
menu_length = 30
menu_prompt = "clipboard"
extra_arguments = []

[log]
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "INFO"
